import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data", "real_data.csv")
OUT = os.path.join(ROOT, "paper", "figures")
os.makedirs(OUT, exist_ok=True)
df = pd.read_csv(DATA)

d118 = df[df["type"] == "ieee118"].copy().sort_values("load")
x118 = d118["load"].tolist()
y118_base = d118["baseline"].tolist()
y118_ctrl = d118["controlled"].tolist()

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))
ax1.plot(x118, y118_base, 'o-', color='red', label='Baseline')
ax1.plot(x118, y118_ctrl, 's-', color='blue', label='Controlled')
ax1.axvspan(30, 50, alpha=0.2, color='gray')
ax1.set_xlabel('Load (MW)')
ax1.set_ylabel('Collapse probability')
ax1.set_title('IEEE-118: Critical band')
ax1.legend()
ax1.grid(True, linestyle='--', alpha=0.5)

baseline_40 = float(d118.loc[d118["load"] == 40, "baseline"].iloc[0])
controlled_40 = float(d118.loc[d118["load"] == 40, "controlled"].iloc[0])
ax2.bar(['Baseline', 'With memory', 'No memory'], [baseline_40, controlled_40, baseline_40], color=['red', 'blue', 'gray'])
ax2.set_ylabel('Collapse probability at 40 MW')
ax2.set_title('Memory ablation')
ax2.set_ylim(0, 0.7)
ax2.text(0, 0.55, f'Δ = {baseline_40 - controlled_40:.3f}', ha='center', color='blue')
ax2.text(2, 0.55, 'Δ = 0', ha='center', color='gray')
plt.tight_layout()
plt.savefig(os.path.join(OUT, 'fig1_ieee118_submission.png'), dpi=300)
plt.close()

d300 = df[df["type"] == "ieee300"].copy().sort_values("load")
x300 = d300["load"].to_numpy()
y300_base = d300["baseline"].to_numpy()
y300_ctrl = d300["controlled"].to_numpy()
delta = y300_base - y300_ctrl

fig, ax1 = plt.subplots(figsize=(8, 5))
ax1.plot(x300, y300_base, 'o-', color='red', label='Baseline')
ax1.plot(x300, y300_ctrl, 's-', color='blue', label='Controlled')
ax1.set_xlabel('Load (MW)')
ax1.set_ylabel('Collapse probability')
ax1.legend(loc='upper left')
ax1.grid(True, linestyle='--', alpha=0.3)
ax1.axvspan(115, 130, alpha=0.15, color='gray', label='Critical band')

ax2 = ax1.twinx()
ax2.plot(x300, delta, 'd-', color='green', linewidth=2, label='Δ')
idx = int(np.argmax(delta))
ax2.plot(x300[idx], delta[idx], 'D', color='darkgreen', markersize=8)
ax2.annotate(f'Peak Δ = {delta[idx]:.3f}', xy=(x300[idx], delta[idx]), xytext=(x300[idx] + 1, delta[idx] + 0.05), arrowprops=dict(arrowstyle='->', color='darkgreen'))
ax2.set_ylabel('Suppression Δ', color='green')
lines1, lab1 = ax1.get_legend_handles_labels()
lines2, lab2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, lab1 + lab2, loc='upper right')
ax1.set_title('IEEE-300: Finite-width band')
plt.tight_layout()
plt.savefig(os.path.join(OUT, 'fig3_ieee300_submission.png'), dpi=300)
plt.close()

dbw = df[df["type"] == "bandwidth"].copy().sort_values("load")
sizes_bw = dbw["load"].to_numpy()
widths = dbw["baseline"].to_numpy()
fig, ax = plt.subplots(figsize=(6, 5))
ax.loglog(sizes_bw, widths, 'o', color='blue', label='Data')
ax.set_xlabel('System size (number of buses)')
ax.set_ylabel('Critical band width (MW)')
ax.set_title('Critical band width for IEEE-118, 300, and 2383 systems')
ax.grid(True, linestyle='--', alpha=0.5)
ax.legend()
plt.tight_layout()
plt.savefig(os.path.join(OUT, 'fig4_width_empirical_submission.png'), dpi=300)
plt.close()

dchi = df[df["type"] == "chi"].copy().sort_values("load")
sizes_chi = dchi["load"].to_numpy()
chi_peaks = dchi["baseline"].to_numpy()
fig, ax = plt.subplots(figsize=(6, 5))
ax.plot(sizes_chi, chi_peaks, 'o-', color='green')
ax.set_xlabel('System size (number of buses)')
ax.set_ylabel(r'Peak susceptibility $\chi_{\mathrm{peak}}$')
ax.set_title('No divergence')
ax.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig(os.path.join(OUT, 'fig5_peak_susceptibility_submission.png'), dpi=300)
plt.close()

print("done")
